In [1]:
import numpy as np

# numpy array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
type(np.array(benimListem))

numpy.ndarray

In [6]:
matrixListesi =[[10,20,30],[20,30,40],[40,50,60]]

In [7]:
matrixListesi[0][1]

20

In [8]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

# arange


In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10) #numpy dizisi gibi olusturur

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# zeros

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2)) #matris gibi

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones(2)

array([1., 1.])

In [15]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# linspace

In [16]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [17]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# eye

In [18]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# random 

In [20]:
np.random.randn(8)

array([ 0.37269438, -0.49031762,  1.65178179,  0.3994836 , -0.74661458,
       -0.3841021 , -1.02514503,  2.18924488])

In [22]:
np.random.randn(8,8)

array([[-0.69298918,  0.04843658,  0.18712342,  0.10634189, -0.41830545,
         0.03176889, -2.47525232, -0.18191905],
       [-0.60950797,  0.35600733, -0.22006183, -0.60093258,  0.19699345,
         0.30339828, -1.60167041,  0.58994148],
       [ 0.49526146,  0.60524226,  0.82976258,  0.04175975,  0.68290175,
         1.47876143, -2.25859704, -0.91877658],
       [ 0.30583551, -0.40435668,  0.45288013,  1.44171367,  0.09643258,
         0.18415443, -0.81893695,  0.68077979],
       [-0.9682172 , -1.41971129, -0.18910154, -0.12710659, -0.33686671,
        -0.16760025,  1.28214398,  0.72101101],
       [ 1.49906406,  0.33817088,  0.39086397, -2.02538444,  0.16085224,
        -1.18607081,  0.15884125,  1.85980675],
       [ 0.19904897,  1.41320658, -0.53573097,  0.17420261,  0.95823264,
         0.09144781, -2.07418055,  0.33461645],
       [ 1.02321839,  0.6088477 ,  0.09916532,  1.8136616 , -0.12795064,
         1.23649685,  1.31794326, -0.74506196]])

In [23]:
np.random.randint(1,10)

7

In [24]:
np.random.randint(1,10,3) # 3 tane random deger

array([4, 7, 5])

In [25]:
benimNumpyDizim  = np.arange(30)

In [26]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
benimRandomDizim = np.random.randint(0,100,20)

In [30]:
benimRandomDizim

array([58, 10, 51, 57, 38, 12, 96, 51, 15, 55, 14, 50, 42, 22, 44, 29, 37,
       37, 43, 88])

# numpy dizi metodları

In [31]:
benimNumpyDizim.reshape(5,6) #30 elemanlı

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
benimNumpyDizim.max()

29

In [33]:
benimRandomDizim.max()

96

In [34]:
benimRandomDizim.min()

10

In [35]:
benimRandomDizim.argmax() # max deger kaçıncı sırada

6

In [36]:
benimRandomDizim.argmin() # min deger kaçıncı sırada

1

In [37]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [38]:
reshapeDizim.shape

(5, 6)

In [39]:
benimRandomDizim.shape

(20,)