In [1]:
import numpy as np

In [2]:
benimDizim = np.arange(0,15)

In [3]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
benimDizim[5]

5

In [6]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [7]:
benimDizim[3:8] = -5

In [8]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
baskaDizi = np.arange(0,24)

In [10]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [13]:
slicingDizisi = baskaDizi[4:9]

In [14]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [15]:
type(slicingDizisi)

numpy.ndarray

In [16]:
slicingDizisi[:] = 700

In [17]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [18]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
ornekDizi = np.arange(0,24)

In [21]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDiziKopyasi = ornekDizi.copy()

In [23]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [25]:
ornekKopyaSlicing = ornekDiziKopyasi[3:6]

In [27]:
ornekKopyaSlicing[:]=800

In [28]:
ornekKopyaSlicing

array([800, 800, 800])

In [29]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [30]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

# matrix

In [31]:
benimListem=[[10,20,30],[40,50,60],[30,40,50]]

In [32]:
benimMatrixDizim = np.array(benimListem)

In [33]:
benimMatrixDizim

array([[10, 20, 30],
       [40, 50, 60],
       [30, 40, 50]])

In [34]:
benimMatrixDizim[1][2]

60

In [35]:
benimMatrixDizim[1,2]

60

In [36]:
benimMatrixDizim[0:,2]

array([30, 60, 50])

In [37]:
benimMatrixDizim[2:,2:]

array([[50]])

In [38]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [40]:
yeniMatrix = np.array(yeniListe)

In [41]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# operasyonlar 

In [43]:
yeniBirDizi = np.arange(5,25)

In [44]:
yeniBirDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [45]:
yeniBirDizi = np.random.randint(1,100,20)

In [46]:
yeniBirDizi

array([37, 69, 46, 91, 90, 55, 44, 19, 16, 30, 46, 59, 45, 55, 24, 90, 65,
       84, 79, 63])

In [47]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [48]:
yeniBirDizi

array([37, 69, 46, 91, 90, 55, 44, 19, 16, 30, 46, 59, 45, 55, 24, 90, 65,
       84, 79, 63])

In [49]:
sonucDizisi = yeniBirDizi > 24

In [50]:
sonucDizisi

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [51]:
yeniBirDizi

array([37, 69, 46, 91, 90, 55, 44, 19, 16, 30, 46, 59, 45, 55, 24, 90, 65,
       84, 79, 63])

In [52]:
yeniBirDizi[sonucDizisi]

array([37, 69, 46, 91, 90, 55, 44, 30, 46, 59, 45, 55, 90, 65, 84, 79, 63])

In [53]:
yeniBirDizi

array([37, 69, 46, 91, 90, 55, 44, 19, 16, 30, 46, 59, 45, 55, 24, 90, 65,
       84, 79, 63])

In [54]:
yeniBirDizi[yeniBirDizi > 24]

array([37, 69, 46, 91, 90, 55, 44, 30, 46, 59, 45, 55, 90, 65, 84, 79, 63])

In [55]:
sonDizi = np.arange(0,24)

In [56]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [57]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [58]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [59]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [60]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [61]:
sonDizi / sonDizi

C:\Users\hatice\AppData\Local\Temp/ipykernel_6060/1312094733.py:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [63]:
np.max(sonDizi)

23

In [64]:
np.min(sonDizi)

0